// CONSTANTS


#define BINDLESS_TEXTURE_BINDING 0
#define BINDLESS_SAMPLER_BINDING 1
#define BINDLESS_STORAGE_IMAGE_BINDING 2
#define MAX_MIPS 16
#define RT_MAX_MIPS 13
#define MAX_SWAPCHAIN_IMAGES 8
#define MAX_FRAMES_IN_FLIGHT 3


#define MAX_PIPELINES                256
#define MAX_BINDLESS_SAMPLERS        256
#define MAX_BINDLESS_TEXTURES        65536

#define MAX_COLOR_ATTACHMENTS 8

